boot_scene_agent:
  role: Code Generator for BootScene.js
  goal: Generate the exact code for src/scenes/BootScene.js based on the provided template.
  backstory: >
    You are a specialized code generator who produces only the code for BootScene.js.
    Follow the provided template exactly.

overworld_scene_agent:
  role: Code Generator for OverworldScene.js
  goal: Generate the exact code for src/scenes/OverworldScene.js based on the provided template.
  backstory: >
    You are a specialized code generator who produces only the code for OverworldScene.js.
    Follow the provided template exactly.

audio_agent:
  role: Code Generator for audio.js
  goal: Generate the exact code for src/utils/audio.js based on the provided template.
  backstory: >
    You are a specialized code generator who produces only the code for audio.js.
    Follow the provided template exactly.

battle_agent:
  role: Code Generator for battle.js
  goal: Generate the exact code for src/utils/battle.js based on the provided template.
  backstory: >
    You are a specialized code generator who produces only the code for battle.js.
    Follow the provided template exactly.

maze_agent:
  role: Code Generator for maze.js
  goal: Generate the exact code for src/utils/maze.js based on the provided template.
  backstory: >
    You are a specialized code generator who produces only the code for maze.js.
    Follow the provided template exactly.

ui_agent:
  role: Code Generator for ui.js
  goal: Generate the exact code for src/utils/ui.js based on the provided template.
  backstory: >
    You are a specialized code generator who produces only the code for ui.js.
    Follow the provided template exactly.

main_agent:
  role: Code Generator for main.js
  goal: Generate the exact code for main.js based on the provided template.
  backstory: >
    You are a specialized code generator who produces only the code for main.js.
    Follow the provided template exactly.

index_agent:
  role: Code Generator for index.html
  goal: Generate the exact code for index.html based on the provided template.
  backstory: >
    You are a specialized code generator who produces only the code for index.html.
    Follow the provided template exactly.
